name: Trigger auto deployment for kedsouza-flask

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/kedsouza-flask-AutoDeployTrigger-3ec3783b-2dcb-43ca-9797-1133bbfd7001.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.KEDSOUZAFLASK_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: kedsouzaacr.azurecr.io
          registryUsername: ${{ secrets.KEDSOUZAFLASK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KEDSOUZAFLASK_REGISTRY_PASSWORD }}
          containerAppName: kedsouza-flask
          resourceGroup: kedsouza-ca
          imageToBuild: kedsouzaacr.azurecr.io/kedsouza-flask:${{ github.sha }}
          
            

     

